### ISSUE TITLE
New numpy version leads to AttributeError

### ISSUE THREAD

**Issue by jakobtroidl** [navis-org/navis#115]
Hi @schlegelp, 

I just spent some time debugging and thought this might be helpful for some other users. 

It seems like Navis is incompatible with `numpy v1.24.0`. However, everything works fine with `numpy v1.23.5`. For `v1.24.0` version, I get the following error message.

```
 File "/Users/jakobtroidl/Desktop/neuronal-motifs/neuronal_motifs/server/vimo/lib/python3.10/site-packages/navis/core/__init__.py", line 17, in <module>
    from .mesh import MeshNeuron
  File "/Users/jakobtroidl/Desktop/neuronal-motifs/neuronal_motifs/server/vimo/lib/python3.10/site-packages/navis/core/mesh.py", line 31, in <module>
    from .. import utils, config, meshes, conversion, graph
  File "/Users/jakobtroidl/Desktop/neuronal-motifs/neuronal_motifs/server/vimo/lib/python3.10/site-packages/navis/conversion/__init__.py", line 15, in <module>
    from .meshing import voxels2mesh
  File "/Users/jakobtroidl/Desktop/neuronal-motifs/neuronal_motifs/server/vimo/lib/python3.10/site-packages/navis/conversion/meshing.py", line 436, in <module>
    def _voxels_to_matrix(voxels, fill=False, pad=1, dtype=np.bool):
  File "/Users/jakobtroidl/Desktop/neuronal-motifs/neuronal_motifs/server/vimo/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?
```

Let me know if I should provide more details. Best, Jakob

**Comment by schlegelp** [comment]
Thanks for the digging, Jakob! I did remove `np.bool` a while back but we also haven't had a new release in almost 6 months and we're overdue for one. I'll check if anything needs wrapping up before we do but for now you could install `navis` from Github to get a working version: 

```bash
$ pip3 install git+https://github.com/navis-org/navis@master
```

**Comment by schlegelp** [comment]
I just released `navis` version `1.4.0` which should fix the issues with `numpy`. Let us know if this does the trick! Please the [change log](https://navis.readthedocs.io/en/latest/source/whats_new.html) for other changes.

**Comment by schlegelp** [comment]
Closing assuming this is solved.
